# This is a basic workflow to help you get started with Actions

name: Linux Build CI

# Controls when the workflow will run
on: workflow_dispatch
jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        actions: write
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true
          
      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.2.0
        with:
          haxe-version: 4.2.5

      # Runs a set of commands using the runners shell
      - name: Installing Libraries
        run: |
          sudo add-apt-repository ppa:haxe/releases -y
          sudo apt-get update
          sudo apt-get install gcc-multilib g++-multilib haxe -y
          haxelib setup ~/haxelib
          haxelib install lime 7.9.0
          haxelib install openfl 9.1.0
          haxelib install flixel 4.11.0
          haxelib run lime setup
          haxelib run lime setup flixel
          haxelib install flixel-tools 1.5.1
          printf "y\n4\n" | haxelib run flixel-tools setup
          haxelib install flixel-addons 2.11.0
          haxelib install flixel-ui 2.4.0
          haxelib install linc_luajit
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git systools https://github.com/haya3218/systools
          haxelib run lime rebuild systools linux
          haxelib git tentools https://github.com/TentaRJ/tentools
          haxelib list

      - name: Building
        run: haxelib run lime build linux -final

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: Linux Build
          path: export/release/linux/bin
          if-no-files-found: warn
