# This is a basic workflow to help you get started with Actions

name: Windows Build CI

# Controls when the workflow will run
on: workflow_dispatch
jobs:
  Build:
    runs-on: macos-13
    permissions:
        contents: write
        actions: write
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
      - uses: krdlab/setup-haxe@v1.2.0
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: script run line haha
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 7.9.0
          haxelib install openfl 9.1.0
          haxelib install flixel 4.11.0
          haxelib run lime setup
          haxelib run lime setup flixel
          haxelib install flixel-tools 1.5.1
          haxelib run flixel-tools setup
          haxelib install flixel-addons 2.11.0
          haxelib install flixel-ui 2.4.0
          haxelib install linc_luajit
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git systools https://github.com/haya3218/systools
          haxelib run lime rebuild systools mac
          haxelib git tentools https://github.com/TentaRJ/tentools
          haxelib list
          haxelib run lime build mac
          tar -zcvf Indie Cross.tar.gz -C export/release/macos/bin .

      - uses: actions/upload-artifact@main
        with:
          name: Windows Build
          path: export/release/windows/bin
